spring:
  application:
    name: barber-shop-api
  datasource:
    url: ${DB_URL:jdbc:postgresql://localhost:5432/barber-shop-api}
    username: ${DB_USER:barber-shop-api}
    password: ${DB_PASSWORD:barber-shop-api}
  jpa:
    hibernate:
      ddl-auto: validate